<center><h1>Computer lab 3: Floats and roundoff errors</h1></center>
<center><h2>Part 1: Zero is not zero, aequal is not equal</h2></center>

_There are infinitely many real numbers between any two numbers (e.g. between 0.0 and 1.0). The real axis number line contains infinitely many numbers. Computers and computer memories are finite, and the real number axis must somehow be represented as a discrete, finite number axis. The result is that all numbers must be rounded when stored or calculated in the computer. This leads sometimes to strange results, and we will look at some of them in this first part of the lab._ <br>
<hr>

<p>First, import the <b>NumPy</b> library.

In [1]:
import numpy as np

<br>
<hr>
<h3>Equal is not equal and zero is not zero!?</h3>

<p><b>Test number 1</b><br>The sum $a = 0.1 + 0.1 + 0.1$ is obviously equal to $b = 0.3$. Just to be sure, do a little check in Python. Define variable <code>a</code> as the sum above, and variable <code>b</code> to 0.3, then check if they are equal (remember, you check equality in Python with the <code>==</code>-operator). Is the equality true or false?
    </p>

In [2]:
# Enter your code here
a = 0.1 + 0.1 + 0.1
b = 0.3
print(a == b)

False


<p>
The result is a bit unexpected! So what is the difference between $a$ and $b$? Check the relative difference <code>rel_diff</code>$= \frac{| a-b |}{|a]}$ (we consider $a$ as 'exact' here, but you can do it the other way around, i.e. consider $b$ to be 'exact').
</p>    

In [24]:
# Enter your code here
rel_diff = (a - b) / b
print(rel_diff)
rel_diff_a = (b - a) / a
print(rel_diff_a)

-0.6666666666666666
1.9999999999999998


<p>The order of magnitude of the relative difference is important here, not the exact number. What order of magnitude did you get?</p>
<p><b>Test number 2</b><br>
 $sin(\pi)$ equals zero (in radians), but what is it in Python? Check below ($\pi$ is a predefined constant in <b>numpy</b>: <code>np.pi</code>).

In [7]:
# Enter your code here
print(np.sin(np.pi))

1.2246467991473532e-16


<p>How much does it differ from zero? What order of magnitude?</p>
<p>
    <b>Test number 3</b><br>
For any (invertible) matrix $A$, the inverse times the matrix itself is equal to the Identity matrix, i.e. $A^{-1}A = A A^{-1} = I$, where $I$ is the identity matrix (ones on the main diagonal and zeros elsewhere).<br>
    Use <code>np.random.rand()</code>, to create a $n \times n$ matrix with random numbers (on the range [0 1]). Let $n=4$ and calculate $A^{-1}A$ and $AA^{-1}$, respectively. Print the results and see if it looks like the identity matrix.
</p>

In [10]:
# Enter your code here
n = 4
A = np.random.rand(n, n)
A_inv = np.linalg.inv(A)
I = A @ A_inv

print(A)
print(A_inv)
print(I)

[[0.89890279 0.57010809 0.42638269 0.0528599 ]
 [0.81905535 0.64104391 0.5993003  0.25634441]
 [0.53026686 0.26203383 0.73190161 0.66531844]
 [0.60825055 0.03698561 0.70584548 0.12159471]]
[[ 5.25393773 -5.35184102  1.72017549 -0.41344368]
 [-3.18561502  5.07603821 -1.56288236 -0.76490399]
 [-4.75679231  4.8803325  -1.88678365  2.10296613]
 [ 2.30003214 -3.10244369  2.82318339 -1.68265003]]
[[ 1.00000000e+00  1.40337685e-15 -2.32596836e-16  6.72730417e-17]
 [-5.93118667e-16  1.00000000e+00  3.69481710e-17  2.73950943e-16]
 [-3.78978688e-16  4.15902371e-16  1.00000000e+00  1.18106054e-16]
 [-1.58847321e-16  6.24904653e-16 -3.14289197e-17  1.00000000e+00]]


<br>
<p>Check the relative errors in the previous computations, $\frac{|| A^{-1}A - I ||}{||I||}$ and $\frac{|| AA^{-1} - I ||}{||I||}$ (you can use any norm). For the exact identity matrix, use <code>np.identity()</code>.
</p>

In [11]:
# Enter your code here
II = np.identity(n)
print(((A_inv @ A) - II) / (II))

[[-9.99200722e-16             inf            -inf             inf]
 [            inf  2.22044605e-16             inf             inf]
 [            inf            -inf  4.44089210e-16             inf]
 [           -inf            -inf            -inf  0.00000000e+00]]


<positron-console-cell-11>:3: RuntimeWarning: divide by zero encountered in divide


<p>
What is the order of magnitude of the relative error? </p>
<p>
When it's many repeated computations (like in the inverse-computations), the error tend to get slightly bigger as the number of repeated computation gets larger. Repeat the computation above, but try out different matrix sizes $n$, for example $n=50$, $n=100$, $n=500$, $n≈1000$.
    </p>

In [12]:
# Enter your code here
n = 500
A = np.random.rand(n, n)
A_inv = np.linalg.inv(A)
I = A @ A_inv

print(A)
print(A_inv)
print(I)

print("----------------")
II = np.identity(n)
print(((A_inv @ A) - II) / (II))

[[0.34574973 0.58231495 0.81773026 ... 0.62914643 0.13495218 0.6546727 ]
 [0.36574731 0.29275004 0.92173519 ... 0.1847413  0.86493359 0.73393373]
 [0.50167203 0.78126607 0.94294681 ... 0.25178953 0.58681911 0.11086969]
 ...
 [0.19487661 0.41243552 0.83207012 ... 0.56762481 0.37359188 0.59380305]
 [0.56112828 0.52307122 0.31112422 ... 0.23859566 0.62292868 0.17324254]
 [0.00978354 0.45551352 0.8910894  ... 0.21554039 0.41148207 0.80948009]]
[[-0.07631644  0.05542552  0.21036862 ... -0.25263675 -0.03061601
  -0.00791479]
 [ 0.07484359 -0.13240244 -0.17570599 ...  0.20146364 -0.16555055
  -0.08813367]
 [ 0.04757571 -0.10289853 -0.11533253 ...  0.14703497 -0.00686073
  -0.06445311]
 ...
 [ 0.23955605 -0.14211122 -0.39047729 ...  0.57794002 -0.05020819
   0.3262481 ]
 [ 0.05174251 -0.13816488 -0.14434296 ...  0.05827701 -0.06286178
   0.20557053]
 [ 0.16849976 -0.05023159 -0.42069829 ...  0.61225948  0.13426769
  -0.64643876]]
[[ 1.00000000e+00 -6.85562718e-15  2.44249065e-15 ...  1.3322676

<positron-console-cell-12>:13: RuntimeWarning: divide by zero encountered in divide
<positron-console-cell-12>:13: RuntimeWarning: invalid value encountered in divide


<br>
<p>The relative error you got in the test examples above was $\approx 10^{-16}$ (if you did it correctly). This is the magnitude of the relative roundoff error and is called <i>machine epsilon</i>, usually denoted $\epsilon_M$. This error is due to rounding of so-called <i>floation point numbers</i> (the way real numbers are represented in the computer). In the next part of this lab we will look more in detail where it comes from.<br>
Note, this is in the very nature of how real numbers are represented in computers. It is not a bug in Python. You’ll see the same kind of thing in all programming languages when you work with so-called floating-point arithmetic. The underlying reason is that the 'mathematical' number axis has infinitely many numbers, and must be approximated with a finite number axis.
    </p>

<p>In most cases the roundoff error is hidden. If you for example print $a=0.1$ and $b = 0.3$ on the screen, Python only display a limited number of decimals, and the numbers are rounded. The result is that you only see <code>0.1</code> and <code>0.3</code>, respectively. It does not mean that the error is gone, it only means that you can't see it.</p>
<p>The code below print $a$ and $b$, displayed in the standard way and displayed with twenty decimal places. You can see the reason why $0.1+0.1+0.1 \neq 0.3$ in floating point addition.</p>

In [13]:
# Run this code
a = 0.1
b = 0.3
print("a=", a, ", and twenty decimal places:", f"{a:.20f}")
print("a=", b, ", and twenty decimal places:", f"{b:.20f}")

a= 0.1 , and twenty decimal places: 0.10000000000000000555
a= 0.3 , and twenty decimal places: 0.29999999999999998890


<br>
<h3>To check if reals are equal</h3>
<p>If we actually would like to check if numbers are equal or not, is that possible? You can for example use a code similar to this:</p>
<pre>
  if a == b:
      print('The numbers are equal')
  else:
      print('The numbers are not equal')
</pre>
<p>However, this would not really work becaues the numbers that should be equal aren't really equal. The <code>==</code> would always result in <code>false</code>.</p>
<p>The usual way to solve this is to check if the relative difference between $a$ and $b$ is less then machine epsilon or a number slightly bigger (for example $100 \cdot \epsilon_M$):
$$|a-b|/|a| < 100 \cdot 10^{-16} \Rightarrow |a - b | < |a| \cdot 100\cdot 10^{-16}.$$<br>
The code would change to
<pre>if abs(a-b) < abs(a)*100*1e-16</pre>
Implement this below and check if it works for $a=0.1+0.1+0.1$ and $b=0.3$.
</p>

In [ ]:
# Enter your code here
if abs(a - b) < abs(a) * 100 * 1e-16:
    print(True)
else:
    print(False)

False


<p>(If $b=0$, this won't work (divide by zero), and you need to switch to absolute difference in that case).</p>
<p>In <b>numpy</b> there is a built-in function for this, <code>np.isclose(a,b,rtol,atol)</code>, where <code>rtol</code> is the relative tolerance, and <code>atol</code> is the absolute tolerance. Change your if-statement and include <code>np.isclose</code> (you can use <code>rtol=1e-14</code>, <code>atol=1e-14</code>):</p>

In [23]:
# Enter your code here
if np.isclose(a, b, rtol=1e-14, atol=1e-14):
    print(True)
else:
    print(False)

False


<p>Does it also work for $a=0$ ? Let $a=0$ and $b=0.1+0.1+0.1-0.3$ and run the code again.</p>
<p>As you can see it also works for $a=0$ or $b=0$. As usual in <b>numpy</b>, the function is defined also for array input arguments.
    </p>

<p>In the next part of the lab we will take a closer look at how the floation point system works</p>
<p>&nbsp;</p>
<hr>